pub struct Strings {
    // footer
    pub select_on: &'static str,
    pub select_copy_hint: &'static str,
    pub select_cursor: &'static str,
    pub select_anchor_hint: &'static str,
    pub help_hint: &'static str,
    // panels
    pub tree_fullscreen: &'static str,
    pub tree_focus: &'static str,
    pub tree_title: &'static str,
    pub preview_select: &'static str,
    pub preview_fullscreen: &'static str,
    pub preview_focus: &'static str,
    pub preview_title: &'static str,
    pub preview_empty: &'static str,
    // mermaid
    pub mermaid_select_title: &'static str,
    pub mermaid_select_hint: &'static str,
    pub mermaid_render_terminal: &'static str,
    pub mermaid_open_html: &'static str,
    pub mermaid_open_web: &'static str,
    pub mermaid_output_title: &'static str,
    pub mermaid_view_title: &'static str,
    // help tabs
    pub tab_shortcuts: &'static str,
    pub tab_settings: &'static str,
    pub help_footer_shortcuts: &'static str,
    pub help_footer_settings: &'static str,
    // shortcuts
    pub nav_section: &'static str,
    pub sc_enter: &'static str,
    pub sc_tab: &'static str,
    pub sc_shift_y: &'static str,
    pub sc_shift_e: &'static str,
    pub sc_shift_r: &'static str,
    pub sc_shift_b: &'static str,
    pub sc_ctrl_shift_c: &'static str,
    pub sc_shift_g: &'static str,
    pub sc_shift_0: &'static str,
    pub sc_shift_1_5: &'static str,
    pub sc_q: &'static str,
    pub preview_section: &'static str,
    pub sc_comma_dot: &'static str,
    pub sc_pgupdn: &'static str,
    pub sc_arrows: &'static str,
    pub sc_shift_arrows: &'static str,
    pub sc_colon: &'static str,
    pub sc_shift_t: &'static str,
    pub sc_brackets: &'static str,
    pub sc_shift_m: &'static str,
    pub sc_question: &'static str,
    // settings
    pub settings_title: &'static str,
    pub settings_only_mds_label: &'static str,
    pub settings_editor_label: &'static str,
    pub settings_language_label: &'static str,
    pub settings_bookmarks_label: &'static str,
    pub settings_only_mds_desc: &'static str,
    pub settings_editor_desc: &'static str,
    pub settings_language_desc: &'static str,
    pub settings_stored: &'static str,
    pub settings_config_path: &'static str,
    // web link
    pub weblink_title: &'static str,
    pub weblink_available: &'static str,
    pub weblink_close: &'static str,
    // toc
    pub toc_title: &'static str,
    // search
    pub search_title: &'static str,
    pub search_no_results: &'static str,
    pub search_results_title: &'static str,
    // dest picker (move / copy)
    pub dest_move_title: &'static str,
    pub dest_copy_title: &'static str,
    // find
    pub find_title: &'static str,
    pub find_placeholder: &'static str,
    pub find_no_results: &'static str,
    pub find_results_suffix: &'static str,
    // create
    pub create_folder: &'static str,
    pub create_file: &'static str,
    pub create_type_title: &'static str,
    pub create_folder_name: &'static str,
    pub create_file_name: &'static str,
    pub create_enter: &'static str,
    // git
    pub git_title: &'static str,
    pub git_hint: &'static str,
    pub git_output_suffix: &'static str,
    pub git_output_hint: &'static str,
    pub git_commit_title: &'static str,
    pub git_commit_hint: &'static str,
}

pub static ES: Strings = Strings {
    select_on: "Select: ON  ",
    select_copy_hint: "y = copiar  Esc = cancelar",
    select_cursor: "Select: cursor  ",
    select_anchor_hint: "y = marcar ancla  Esc = cancelar",
    help_hint: "== Para Ayuda presiona: ? ==",
    tree_fullscreen: "Docs [pantalla completa]",
    tree_focus: "Docs [foco]",
    tree_title: "Docs",
    preview_select: "Preview [seleccion]",
    preview_fullscreen: "Preview [pantalla completa]",
    preview_focus: "Preview [foco]",
    preview_title: "Preview",
    preview_empty: "Selecciona un archivo Markdown para ver el contenido",
    mermaid_select_title: "Seleccionar Mermaid",
    mermaid_select_hint: "Arriba/Abajo elegir | Enter abrir | Esc cancelar",
    mermaid_render_terminal: "Render terminal",
    mermaid_open_html: "Abrir HTML",
    mermaid_open_web: "Abrir web link",
    mermaid_output_title: "Salida Mermaid",
    mermaid_view_title: "Mermaid [Esc] hjkl/flechas=mover  Tab=nodo",
    tab_shortcuts: "Atajos",
    tab_settings: "Ajustes",
    help_footer_shortcuts: "Izq/Der cambiar seccion | ? o Esc cerrar",
    help_footer_settings: "↑↓ seleccionar | Enter cambiar | Izq/Der secciones | ? o Esc cerrar",
    nav_section: "Navegacion",
    sc_enter: "abrir archivo o expandir carpeta",
    sc_tab: "cambiar foco entre arbol y preview",
    sc_shift_y: "activar cursor de seleccion  (y=ancla, y=copiar)",
    sc_shift_e: "abrir editor sobre el archivo actual",
    sc_shift_r: "renombrar archivo o carpeta",
    sc_shift_b: "marcar/desmarcar bookmark",
    sc_ctrl_shift_c: "copiar ruta del archivo seleccionado",
    sc_shift_g: "dejar pendiente cd al directorio del item",
    sc_shift_0: "pantalla completa del panel enfocado",
    sc_shift_1_5: "ajustar proporcion entre paneles",
    sc_q: "salir",
    preview_section: "Preview",
    sc_comma_dot: "scroll del documento (linea a linea)",
    sc_pgupdn: "scroll del documento (salto rapido)",
    sc_arrows: "mover cursor en modo seleccion",
    sc_shift_arrows: "extender seleccion en modo seleccion",
    sc_colon: "abrir command palette",
    sc_shift_t: "tabla de contenidos del archivo",
    sc_brackets: "navegar links del preview  Enter=abrir",
    sc_shift_m: "abrir acciones Mermaid",
    sc_question: "abrir o cerrar este menu",
    settings_title: "Configuracion",
    settings_only_mds_label: "Solo Mds   ",
    settings_editor_label: "Editor     ",
    settings_language_label: "Idioma     ",
    settings_bookmarks_label: "Bookmarks  ",
    settings_only_mds_desc: "Solo Mds: cuando esta ON el arbol muestra solo archivos .md.",
    settings_editor_desc: "Editor: nano o vim, se usa al presionar Shift+E.",
    settings_language_desc: "Idioma: es=Espanol, en=English.",
    settings_stored: "Esta configuracion se guarda por usuario.",
    settings_config_path: "Ruta config: ",
    weblink_title: "Web Link",
    weblink_available: "Link Manual Disponible:",
    weblink_close: "Enter o Esc para cerrar",
    toc_title: "Tabla de contenidos  Enter=ir | T/Esc=cerrar",
    search_title: "Buscar archivo",
    search_no_results: "Sin resultados",
    search_results_title: "Resultados  Arriba/Abajo navegar | Enter abrir | Esc cerrar",
    dest_move_title: "Mover a  (l/→ entrar · h/← salir · Enter confirmar · Esc cancelar)",
    dest_copy_title: "Copiar a  (l/→ entrar · h/← salir · Enter confirmar · Esc cancelar)",
    find_title: "Buscar en archivo  (Esc cerrar | Enter saltar)",
    find_placeholder: "Escribe para buscar...",
    find_no_results: "Sin resultados",
    find_results_suffix: "resultado(s)  ↑↓ navegar",
    create_folder: "Carpeta",
    create_file: "Archivo",
    create_type_title: "Tipo  (↑↓ elegir | Enter confirmar | Esc cancelar)",
    create_folder_name: "Nombre carpeta",
    create_file_name: "Nombre archivo",
    create_enter: "Enter crear",
    git_title: "Git  (↑↓ navegar | Enter ejecutar | Esc cerrar)",
    git_hint: "  ↑↓ navegar  Enter ejecutar  Esc cerrar",
    git_output_suffix: "↑↓ scroll | Esc volver",
    git_output_hint: "  ↑↓ / j k  scroll    Esc volver",
    git_commit_title: "Mensaje de commit  (Enter confirmar | Esc cancelar)",
    git_commit_hint: "  Enter confirmar   Esc cancelar",
};

pub static EN: Strings = Strings {
    select_on: "Select: ON  ",
    select_copy_hint: "y = copy  Esc = cancel",
    select_cursor: "Select: cursor  ",
    select_anchor_hint: "y = set anchor  Esc = cancel",
    help_hint: "== For Help Type: ? ==",
    tree_fullscreen: "Docs [fullscreen]",
    tree_focus: "Docs [focus]",
    tree_title: "Docs",
    preview_select: "Preview [select]",
    preview_fullscreen: "Preview [fullscreen]",
    preview_focus: "Preview [focus]",
    preview_title: "Preview",
    preview_empty: "Select a Markdown file to view its content",
    mermaid_select_title: "Select Mermaid",
    mermaid_select_hint: "Up/Down choose | Enter open | Esc cancel",
    mermaid_render_terminal: "Render terminal",
    mermaid_open_html: "Open HTML",
    mermaid_open_web: "Open web link",
    mermaid_output_title: "Mermaid Output",
    mermaid_view_title: "Mermaid [Esc] hjkl/arrows=pan  Tab=node",
    tab_shortcuts: "Shortcuts",
    tab_settings: "Settings",
    help_footer_shortcuts: "Left/Right switch sections | ? or Esc close",
    help_footer_settings: "↑↓ select | Enter toggle | Left/Right switch sections | ? or Esc close",
    nav_section: "Navigation",
    sc_enter: "open file or expand folder",
    sc_tab: "switch focus between tree and preview",
    sc_shift_y: "activate selection cursor  (y=anchor, y=copy)",
    sc_shift_e: "open editor on current file",
    sc_shift_r: "rename file or folder",
    sc_shift_b: "toggle bookmark",
    sc_ctrl_shift_c: "copy selected file path",
    sc_shift_g: "queue cd to item directory",
    sc_shift_0: "fullscreen focused panel",
    sc_shift_1_5: "adjust panel proportion",
    sc_q: "quit",
    preview_section: "Preview",
    sc_comma_dot: "scroll document (line by line)",
    sc_pgupdn: "scroll document (fast jump)",
    sc_arrows: "move cursor in selection mode",
    sc_shift_arrows: "extend selection in selection mode",
    sc_colon: "open command palette",
    sc_shift_t: "table of contents",
    sc_brackets: "navigate preview links  Enter=open",
    sc_shift_m: "open Mermaid actions",
    sc_question: "open or close this menu",
    settings_title: "Configuration",
    settings_only_mds_label: "Only Mds   ",
    settings_editor_label: "Editor     ",
    settings_language_label: "Language   ",
    settings_bookmarks_label: "Bookmarks  ",
    settings_only_mds_desc: "Only Mds: when ON the tree shows only .md files.",
    settings_editor_desc: "Editor: nano or vim, used when pressing Shift+E.",
    settings_language_desc: "Language: es=Espanol, en=English.",
    settings_stored: "This setting is stored per user.",
    settings_config_path: "Config path: ",
    weblink_title: "Web Link",
    weblink_available: "Manual Link Available:",
    weblink_close: "Enter or Esc to close",
    toc_title: "Table of contents  Enter=go | T/Esc=close",
    search_title: "Search file",
    search_no_results: "No results",
    search_results_title: "Results  Up/Down navigate | Enter open | Esc close",
    dest_move_title: "Move to  (l/→ enter · h/← up · Enter confirm · Esc cancel)",
    dest_copy_title: "Copy to  (l/→ enter · h/← up · Enter confirm · Esc cancel)",
    find_title: "Find in file  (Esc close | Enter jump)",
    find_placeholder: "Type to search...",
    find_no_results: "No results",
    find_results_suffix: "result(s)  ↑↓ navigate",
    create_folder: "Folder",
    create_file: "File",
    create_type_title: "Type  (↑↓ choose | Enter confirm | Esc cancel)",
    create_folder_name: "Folder name",
    create_file_name: "File name",
    create_enter: "Enter create",
    git_title: "Git  (↑↓ navigate | Enter run | Esc close)",
    git_hint: "  ↑↓ navigate  Enter run  Esc close",
    git_output_suffix: "↑↓ scroll | Esc back",
    git_output_hint: "  ↑↓ / j k  scroll    Esc back",
    git_commit_title: "Commit message  (Enter confirm | Esc cancel)",
    git_commit_hint: "  Enter confirm   Esc cancel",
};

pub fn get(lang: &str) -> &'static Strings {
    if lang == "en" {
        &EN
    } else {
        &ES
    }
}
